const PDFJS_VERSION='4.10.38';
const pdfjsLib=await import(`https://cdn.jsdelivr.net/npm/pdfjs-dist@${PDFJS_VERSION}/build/pdf.min.mjs`);
pdfjsLib.GlobalWorkerOptions.workerSrc=`https://cdn.jsdelivr.net/npm/pdfjs-dist@${PDFJS_VERSION}/build/pdf.worker.min.mjs`;

const $=s=>document.querySelector(s);
const els={fileInput:$('#fileInput'),importStatus:$('#importStatus'),workspace:$('#workspace'),documentTitle:$('#documentTitle'),navigationList:$('#navigationList'),tabs:[...document.querySelectorAll('.tab')],stage:$('#stage'),scriptDisplay:$('#scriptDisplay'),locationText:$('#locationText'),pageText:$('#pageText'),progressText:$('#progressText'),previousButton:$('#previousButton'),nextButton:$('#nextButton'),rewindButton:$('#rewindButton'),forwardButton:$('#forwardButton'),playButton:$('#playButton'),speedInput:$('#speedInput'),speedValue:$('#speedValue'),fontInput:$('#fontInput'),fontValue:$('#fontValue'),lineHeightInput:$('#lineHeightInput'),lineHeightValue:$('#lineHeightValue'),themeButton:$('#themeButton'),fullscreenButton:$('#fullscreenButton'),exitPresentationButton:$('#exitPresentationButton')};
let model=null,playing=false,animation=0,lastTime=0,scrollPosition=0,navMode='acts',currentPage=1;

const ACT=/^(ERSTER|ZWEITER|DRITTER|VIERTER|FÜNFTER|SECHSTER|SIEBTER|ACHTER|NEUNTER|ZEHNTER)\s+AKT\b/i;
const SCENE=/^(\d+\.|ERSTE|ZWEITE|DRITTE|VIERTE|FÜNFTE|SECHSTE|SIEBTE|ACHTE|NEUNTE|ZEHNTE)\s+SZENE\b/i;
const PAGE_HEADER=/^DIE\s+RÄUBER\s*[·•-]\s*BÜHNENMANUSKRIPT$/i;
const PAGE_NUMBER=/^Seite\s+(\d+)$/i;
const LINE_NUMBER=/^(5|10|15|20|25|30|35|40|45|50)$/;
const clean=v=>String(v||'').replace(/\u00ad/g,'').replace(/[ \t]+/g,' ').replace(/\s+([,.;!?])/g,'$1').trim();

function isSpeaker(text){if(text.length>70||!/[A-ZÄÖÜ]/.test(text))return false;const base=text.replace(/\([^)]*\)/g,'').trim();return base===base.toUpperCase()&&/^[A-ZÄÖÜ0-9 .,'’\-]+$/.test(base)&&!ACT.test(base)&&!SCENE.test(base)}
function classify(text,previous){if(ACT.test(text))return'act';if(SCENE.test(text))return'scene';if(isSpeaker(text))return'speaker';if(/^\(.+\)$/.test(text)||/^(Auftritt|Abgang|Alle ab|Pause\.?$)/i.test(text))return'direction';if(previous&&['act','scene'].includes(previous.type))return'setting';return'dialogue'}
function usable(text){return text&&!PAGE_HEADER.test(text)&&!PAGE_NUMBER.test(text)&&!LINE_NUMBER.test(text)}

function makeModel(rawPages,title,source){const paragraphs=[],pages=[];let act=null,scene=null;rawPages.forEach((raw,pageIndex)=>{const lines=raw.map(clean).filter(usable);const firstIndex=paragraphs.length;for(const text of lines){const type=classify(text,paragraphs.at(-1));if(type==='act'){act=text.toUpperCase();scene=null}if(type==='scene')scene=text.toUpperCase();paragraphs.push({text,type,page:pageIndex+1,act,scene,index:paragraphs.length})}if(paragraphs.length>firstIndex)pages.push({page:pages.length+1,firstIndex,lastIndex:paragraphs.length-1})});const acts=paragraphs.filter(p=>p.type==='act').map(p=>({text:p.text,index:p.index,page:p.page}));const scenes=paragraphs.filter(p=>p.type==='scene').map(p=>({text:p.text,index:p.index,page:p.page,act:p.act}));return{title:title||'Theatertext',source,paragraphs,pages,acts,scenes,pageCount:pages.length}}
function logicalPages(lines,fileName,explicitPages){const isRauber=/räuber|raeuber/i.test(fileName)||lines.some(x=>/^DIE RÄUBER$/i.test(clean(x)));if(explicitPages.length>=Math.max(3,Math.ceil(lines.length/80)))return explicitPages;const target=isRauber&&lines.length>1200?64:Math.max(1,Math.ceil(lines.length/24));const size=Math.ceil(lines.length/target),pages=[];for(let i=0;i<lines.length;i+=size)pages.push(lines.slice(i,i+size));return pages}

async function parseDocx(file){if(!window.JSZip)throw new Error('Das DOCX-Modul konnte nicht geladen werden.');const zip=await JSZip.loadAsync(await file.arrayBuffer());const xml=await zip.file('word/document.xml')?.async('text');if(!xml)throw new Error('Die DOCX-Datei enthält keinen lesbaren Dokumenttext.');const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror'))throw new Error('Die DOCX-Struktur ist beschädigt.');const ns='http://schemas.openxmlformats.org/wordprocessingml/2006/main',body=doc.getElementsByTagNameNS(ns,'body')[0];if(!body)throw new Error('Kein Dokumentkörper gefunden.');const all=[],explicit=[[]];let current=explicit[0];for(const p of [...body.children].filter(n=>n.localName==='p')){const before=p.getElementsByTagNameNS(ns,'pageBreakBefore').length>0;if(before&&current.length){current=[];explicit.push(current)}const text=clean([...p.getElementsByTagNameNS(ns,'t')].map(n=>n.textContent).join(''));if(text){all.push(text);current.push(text)}const pageBreak=[...p.getElementsByTagNameNS(ns,'br')].some(n=>(n.getAttributeNS(ns,'type')||n.getAttribute('w:type'))==='page');if(pageBreak&&current.length){current=[];explicit.push(current)}}const pages=logicalPages(all,file.name,explicit.filter(p=>p.length));return makeModel(pages,file.name.replace(/\.docx$/i,''),'DOCX')}

function pdfRows(items){const rows=[];for(const item of [...items].sort((a,b)=>Math.abs(b.transform[5]-a.transform[5])>3?b.transform[5]-a.transform[5]:a.transform[4]-b.transform[4])){const y=item.transform[5];let row=rows.find(r=>Math.abs(r.y-y)<3);if(!row){row={y,items:[]};rows.push(row)}row.items.push(item)}return rows.sort((a,b)=>b.y-a.y).map(r=>r.items.sort((a,b)=>a.transform[4]-b.transform[4]).map(i=>i.str).join(' '))}
async function parsePdf(file){const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();pages.push(pdfRows(content.items))}if(pages.reduce((n,p)=>n+p.join('').length,0)<50)throw new Error('Diese PDF enthält kaum auswählbaren Text. Eingescannte PDFs benötigen vorher OCR.');return makeModel(pages,file.name.replace(/\.pdf$/i,''),'PDF')}

async function importFile(file){if(!file)return;stop();els.importStatus.textContent=`${file.name} wird gelesen …`;try{const name=file.name.toLowerCase();model=name.endsWith('.docx')?await parseDocx(file):name.endsWith('.pdf')?await parsePdf(file):null;if(!model)throw new Error('Bitte eine DOCX- oder PDF-Datei auswählen.');if(!model.paragraphs.length)throw new Error('Kein verwendbarer Text gefunden.');els.documentTitle.textContent=model.title;els.workspace.classList.remove('hidden');renderScript();renderNavigation();requestAnimationFrame(()=>jumpToPage(1,'auto'));els.importStatus.textContent=`${model.source}: ${model.paragraphs.length} Absätze · ${model.acts.length} Akte · ${model.scenes.length} Szenen · ${model.pageCount} Seiten.`;window.__TELEPROMPTER__={getState:()=>({title:model.title,source:model.source,paragraphs:model.paragraphs.length,acts:model.acts.length,scenes:model.scenes.length,pages:model.pageCount,currentPage,playing,scrollTop:els.stage.scrollTop})}}catch(error){console.error(error);els.importStatus.textContent=`Fehler: ${error.message}`}}
function renderScript(){els.scriptDisplay.replaceChildren(...model.paragraphs.map(p=>{const n=document.createElement('p');n.className=`script-line ${p.type}`;n.dataset.index=p.index;n.textContent=p.text;return n}))}
function renderNavigation(){const source=navMode==='acts'?model.acts:navMode==='scenes'?model.scenes:model.pages;els.navigationList.replaceChildren(...source.map(item=>{const b=document.createElement('button');b.type='button';b.textContent=navMode==='pages'?`Seite ${item.page}`:item.text;b.addEventListener('click',()=>navMode==='pages'?jumpToPage(item.page):jumpToIndex(item.index));return b}))}
function jumpToIndex(index,behavior='smooth'){const n=els.scriptDisplay.querySelector(`[data-index="${index}"]`);if(n){stop();const top=Math.max(0,n.offsetTop-els.stage.clientHeight/2);scrollPosition=top;els.stage.scrollTo({top,behavior})}}
function jumpToPage(page,behavior='smooth'){if(!model)return;currentPage=Math.max(1,Math.min(model.pageCount,Number(page)||1));jumpToIndex(model.pages[currentPage-1].firstIndex,behavior);requestAnimationFrame(updatePosition)}
function updatePosition(){if(!model)return;const guide=els.stage.scrollTop+els.stage.clientHeight/2;let active=model.paragraphs[0];for(const node of els.scriptDisplay.children){if(node.offsetTop<=guide)active=model.paragraphs[Number(node.dataset.index)];else break}currentPage=active?.page||1;els.pageText.textContent=`Seite ${currentPage}`;els.locationText.textContent=[active?.act,active?.scene].filter(Boolean).join(' · ')||model.title;const max=Math.max(1,els.stage.scrollHeight-els.stage.clientHeight);els.progressText.textContent=`${Math.round(els.stage.scrollTop/max*100)} %`}
function stop(){playing=false;cancelAnimationFrame(animation);animation=0;scrollPosition=els.stage?.scrollTop||0;if(els.playButton)els.playButton.textContent='Start'}
function togglePlay(){if(!model)return;if(playing){stop();return}const max=Math.max(0,els.stage.scrollHeight-els.stage.clientHeight);if(els.stage.scrollTop>=max-1){els.stage.scrollTop=0;scrollPosition=0}playing=true;els.playButton.textContent='Pause';scrollPosition=els.stage.scrollTop;lastTime=performance.now();animation=requestAnimationFrame(frame)}
function frame(now){if(!playing)return;const dt=Math.min((now-lastTime)/1000,0.1);lastTime=now;scrollPosition+=Number(els.speedInput.value)*dt;const max=Math.max(0,els.stage.scrollHeight-els.stage.clientHeight);if(scrollPosition>=max){els.stage.scrollTop=max;updatePosition();stop();return}els.stage.scrollTop=scrollPosition;updatePosition();animation=requestAnimationFrame(frame)}
function skip(seconds){stop();scrollPosition=Math.max(0,Math.min(els.stage.scrollHeight-els.stage.clientHeight,els.stage.scrollTop+Number(els.speedInput.value)*seconds));els.stage.scrollTop=scrollPosition;updatePosition()}
function controls(){els.speedValue.textContent=els.speedInput.value;els.fontValue.textContent=els.fontInput.value;els.lineHeightValue.textContent=Number(els.lineHeightInput.value).toFixed(2);els.scriptDisplay.style.fontSize=`${els.fontInput.value}px`;els.scriptDisplay.style.lineHeight=els.lineHeightInput.value}
async function presentation(){if(document.fullscreenElement){await document.exitFullscreen().catch(()=>{});document.body.classList.remove('presentation')}else if(document.fullscreenEnabled){await document.documentElement.requestFullscreen().catch(()=>document.body.classList.add('presentation'))}else document.body.classList.toggle('presentation');els.fullscreenButton.textContent=document.body.classList.contains('presentation')||document.fullscreenElement?'Vollbild verlassen':'Vollbild'}

els.fileInput.addEventListener('change',()=>importFile(els.fileInput.files[0]));els.tabs.forEach(tab=>tab.addEventListener('click',()=>{navMode=tab.dataset.mode;els.tabs.forEach(t=>t.classList.toggle('active',t===tab));renderNavigation()}));els.previousButton.addEventListener('click',()=>jumpToPage(currentPage-1));els.nextButton.addEventListener('click',()=>jumpToPage(currentPage+1));els.rewindButton.addEventListener('click',()=>skip(-10));els.forwardButton.addEventListener('click',()=>skip(10));els.playButton.addEventListener('click',togglePlay);[els.speedInput,els.fontInput,els.lineHeightInput].forEach(i=>i.addEventListener('input',controls));els.stage.addEventListener('scroll',()=>{if(!playing)scrollPosition=els.stage.scrollTop;updatePosition()},{passive:true});els.themeButton.addEventListener('click',()=>{document.body.classList.toggle('light');els.themeButton.textContent=document.body.classList.contains('light')?'Dunkler Modus':'Heller Modus'});els.fullscreenButton.addEventListener('click',presentation);els.exitPresentationButton.addEventListener('click',presentation);document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('presentation')});window.addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(e.code==='Space'){e.preventDefault();togglePlay()}if(e.key==='ArrowRight')jumpToPage(currentPage+1);if(e.key==='ArrowLeft')jumpToPage(currentPage-1);if(e.key.toLowerCase()==='f')presentation()});controls();