const PDFJS_VERSION='4.10.38';
const pdfjsLib=await import(`https://cdn.jsdelivr.net/npm/pdfjs-dist@${PDFJS_VERSION}/build/pdf.min.mjs`);
pdfjsLib.GlobalWorkerOptions.workerSrc=`https://cdn.jsdelivr.net/npm/pdfjs-dist@${PDFJS_VERSION}/build/pdf.worker.min.mjs`;

const $=selector=>document.querySelector(selector);
const els={fileInput:$('#fileInput'),importStatus:$('#importStatus'),importPanel:$('#importPanel'),workspace:$('#workspace'),documentTitle:$('#documentTitle'),navigationList:$('#navigationList'),tabs:[...document.querySelectorAll('.tab')],stage:$('#stage'),scriptDisplay:$('#scriptDisplay'),locationText:$('#locationText'),pageText:$('#pageText'),progressText:$('#progressText'),previousButton:$('#previousButton'),nextButton:$('#nextButton'),rewindButton:$('#rewindButton'),forwardButton:$('#forwardButton'),playButton:$('#playButton'),speedInput:$('#speedInput'),speedValue:$('#speedValue'),fontInput:$('#fontInput'),fontValue:$('#fontValue'),lineHeightInput:$('#lineHeightInput'),lineHeightValue:$('#lineHeightValue'),themeButton:$('#themeButton'),fullscreenButton:$('#fullscreenButton'),exitPresentationButton:$('#exitPresentationButton')};

let model=null;let playing=false;let animation=null;let lastTime=0;let navMode='acts';let currentPage=1;

const ACT=/^(ERSTER|ZWEITER|DRITTER|VIERTER|FÜNFTER|SECHSTER|SIEBTER|ACHTER|NEUNTER|ZEHNTER)\s+AKT\b/i;
const SCENE=/^(\d+\.|ERSTE|ZWEITE|DRITTE|VIERTE|FÜNFTE|SECHSTE|SIEBTE|ACHTE|NEUNTE|ZEHNTE)\s+SZENE\b/i;
const PAGE_HEADER=/^DIE\s+RÄUBER\s*[·•-]\s*BÜHNENMANUSKRIPT$/i;
const PAGE_NUMBER=/^Seite\s+(\d+)$/i;
const LINE_NUMBER=/^(5|10|15|20|25|30|35|40|45|50)$/;

function cleanText(value){return value.replace(/\u00ad/g,'').replace(/[ \t]+/g,' ').replace(/\s+([,.;!?])/g,'$1').trim()}
function isLikelySpeaker(text){if(text.length>65||!/[A-ZÄÖÜ]/.test(text))return false;const base=text.replace(/\([^)]*\)/g,'').trim();return base===base.toUpperCase()&&/^[A-ZÄÖÜ0-9 .,'’\-]+$/.test(base)&&!ACT.test(base)&&!SCENE.test(base)}
function classify(text,index,previous){if(ACT.test(text))return'act';if(SCENE.test(text))return'scene';if(isLikelySpeaker(text))return'speaker';if(/^\(.+\)$/.test(text)||/^(Auftritt|Abgang|Alle ab|Pause\.?$)/i.test(text))return'direction';if(previous&&['act','scene'].includes(previous.type)&&index<previous.index+4)return'setting';return'dialogue'}

function normalizeLines(rawPages,title){const paragraphs=[];const pages=[];let act=null,scene=null;rawPages.forEach((rawLines,pageIndex)=>{const filtered=[];for(const raw of rawLines){const text=cleanText(raw);if(!text||PAGE_HEADER.test(text)||LINE_NUMBER.test(text))continue;const pageMatch=text.match(PAGE_NUMBER);if(pageMatch)continue;filtered.push(text)}const firstIndex=paragraphs.length;for(const text of filtered){const previous=paragraphs.at(-1);const type=classify(text,paragraphs.length,previous);if(type==='act'){act=text.toUpperCase();scene=null}if(type==='scene')scene=text.toUpperCase();paragraphs.push({text,type,page:pageIndex+1,act,scene,index:paragraphs.length})}pages.push({page:pageIndex+1,firstIndex,lastIndex:Math.max(firstIndex,paragraphs.length-1),act,scene})});const acts=paragraphs.filter(p=>p.type==='act').map(p=>({text:p.text,index:p.index,page:p.page}));const scenes=paragraphs.filter(p=>p.type==='scene').map(p=>({text:p.text,index:p.index,page:p.page,act:p.act}));return{title:title||'Theatertext',paragraphs,pages,acts,scenes,pageCount:pages.length}}

async function parseDocx(file){if(!window.JSZip)throw new Error('DOCX-Modul konnte nicht geladen werden.');const zip=await JSZip.loadAsync(await file.arrayBuffer());const xml=await zip.file('word/document.xml')?.async('text');if(!xml)throw new Error('Die DOCX-Datei enthält keinen lesbaren Dokumenttext.');const doc=new DOMParser().parseFromString(xml,'application/xml');const ns='http://schemas.openxmlformats.org/wordprocessingml/2006/main';const body=doc.getElementsByTagNameNS(ns,'body')[0];const pages=[[]];let current=pages[0];for(const child of body.children){if(child.localName!=='p')continue;const breaks=[...child.getElementsByTagNameNS(ns,'br')].filter(node=>node.getAttributeNS(ns,'type')==='page'||node.getAttribute('w:type')==='page');if(breaks.length&&current.length){current=[];pages.push(current)}const text=[...child.getElementsByTagNameNS(ns,'t')].map(node=>node.textContent).join('');if(cleanText(text))current.push(text);const pageBreakBefore=child.getElementsByTagNameNS(ns,'pageBreakBefore').length>0;if(pageBreakBefore&&current.length){current=[];pages.push(current)}}return normalizeLines(pages.filter(page=>page.length),file.name.replace(/\.docx$/i,''))}

function groupPdfItems(items){const rows=[];const sorted=[...items].sort((a,b)=>Math.abs(b.transform[5]-a.transform[5])>3?b.transform[5]-a.transform[5]:a.transform[4]-b.transform[4]);for(const item of sorted){const y=item.transform[5];let row=rows.find(entry=>Math.abs(entry.y-y)<3);if(!row){row={y,items:[]};rows.push(row)}row.items.push(item)}return rows.sort((a,b)=>b.y-a.y).map(row=>row.items.sort((a,b)=>a.transform[4]-b.transform[4]).map(item=>item.str).join(' '))}
async function parsePdf(file){const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const content=await page.getTextContent();pages.push(groupPdfItems(content.items))}const total=pages.reduce((sum,page)=>sum+page.join('').length,0);if(total<50)throw new Error('Diese PDF enthält kaum auswählbaren Text. Eingescannte PDFs benötigen vorher eine OCR-Erkennung.');return normalizeLines(pages,file.name.replace(/\.pdf$/i,''))}

async function importFile(file){if(!file)return;els.importStatus.textContent=`${file.name} wird gelesen …`;try{const lower=file.name.toLowerCase();if(lower.endsWith('.docx'))model=await parseDocx(file);else if(lower.endsWith('.pdf'))model=await parsePdf(file);else throw new Error('Bitte eine DOCX- oder PDF-Datei auswählen.');if(!model.paragraphs.length)throw new Error('Kein verwendbarer Text gefunden.');els.documentTitle.textContent=model.title;els.workspace.classList.remove('hidden');renderScript();renderNavigation();requestAnimationFrame(()=>jumpToPage(1));els.importStatus.textContent=`Geladen: ${model.paragraphs.length} Absätze, ${model.acts.length} Akte, ${model.scenes.length} Szenen, ${model.pageCount} Seiten.`}catch(error){console.error(error);els.importStatus.textContent=`Fehler: ${error.message}`}}
function renderScript(){els.scriptDisplay.replaceChildren(...model.paragraphs.map(p=>{const node=document.createElement('p');node.className=`script-line ${p.type}`;node.dataset.index=p.index;node.dataset.page=p.page;node.textContent=p.text;return node}))}
function renderNavigation(){const source=navMode==='acts'?model.acts:navMode==='scenes'?model.scenes:model.pages;els.navigationList.replaceChildren(...source.map(item=>{const button=document.createElement('button');button.type='button';button.textContent=navMode==='pages'?`Seite ${item.page}`:item.text;button.addEventListener('click',()=>navMode==='pages'?jumpToPage(item.page):jumpToIndex(item.index));return button}))}
function jumpToIndex(index){const node=els.scriptDisplay.querySelector(`[data-index="${index}"]`);if(node)els.stage.scrollTo({top:Math.max(0,node.offsetTop-els.stage.clientHeight/2),behavior:'smooth'})}
function jumpToPage(page){if(!model)return;const value=Math.max(1,Math.min(model.pageCount,Number(page)||1));const target=model.pages[value-1];currentPage=value;jumpToIndex(target.firstIndex);updatePosition()}
function updatePosition(){if(!model)return;const guide=els.stage.scrollTop+els.stage.clientHeight/2;let active=model.paragraphs[0];for(const node of els.scriptDisplay.children){if(node.offsetTop<=guide)active=model.paragraphs[Number(node.dataset.index)];else break}currentPage=active?.page||1;els.pageText.textContent=`Seite ${currentPage}`;els.locationText.textContent=[active?.act,active?.scene].filter(Boolean).join(' · ')||model.title;const max=Math.max(1,els.stage.scrollHeight-els.stage.clientHeight);els.progressText.textContent=`${Math.round(els.stage.scrollTop/max*100)} %`}
function togglePlay(){playing=!playing;els.playButton.textContent=playing?'Pause':'Start';lastTime=performance.now();if(playing)animation=requestAnimationFrame(scrollFrame);else cancelAnimationFrame(animation)}
function scrollFrame(now){if(!playing)return;const dt=(now-lastTime)/1000;lastTime=now;els.stage.scrollTop+=Number(els.speedInput.value)*dt;updatePosition();if(els.stage.scrollTop>=els.stage.scrollHeight-els.stage.clientHeight){playing=false;els.playButton.textContent='Start';return}animation=requestAnimationFrame(scrollFrame)}
function skip(seconds){els.stage.scrollTop+=Number(els.speedInput.value)*seconds;updatePosition()}
function updateControls(){els.speedValue.textContent=els.speedInput.value;els.fontValue.textContent=els.fontInput.value;els.lineHeightValue.textContent=Number(els.lineHeightInput.value).toFixed(2);els.scriptDisplay.style.fontSize=`${els.fontInput.value}px`;els.scriptDisplay.style.lineHeight=els.lineHeightInput.value}
async function togglePresentation(){if(document.fullscreenElement){await document.exitFullscreen().catch(()=>{});document.body.classList.remove('presentation')}else if(document.fullscreenEnabled){await document.documentElement.requestFullscreen().catch(()=>document.body.classList.add('presentation'))}else document.body.classList.toggle('presentation');els.fullscreenButton.textContent=document.body.classList.contains('presentation')||document.fullscreenElement?'Vollbild verlassen':'Vollbild'}

els.fileInput.addEventListener('change',()=>importFile(els.fileInput.files[0]));els.tabs.forEach(tab=>tab.addEventListener('click',()=>{navMode=tab.dataset.mode;els.tabs.forEach(t=>t.classList.toggle('active',t===tab));renderNavigation()}));els.previousButton.addEventListener('click',()=>jumpToPage(currentPage-1));els.nextButton.addEventListener('click',()=>jumpToPage(currentPage+1));els.rewindButton.addEventListener('click',()=>skip(-10));els.forwardButton.addEventListener('click',()=>skip(10));els.playButton.addEventListener('click',togglePlay);[els.speedInput,els.fontInput,els.lineHeightInput].forEach(input=>input.addEventListener('input',updateControls));els.stage.addEventListener('scroll',updatePosition,{passive:true});els.themeButton.addEventListener('click',()=>{document.body.classList.toggle('light');els.themeButton.textContent=document.body.classList.contains('light')?'Dunkler Modus':'Heller Modus'});els.fullscreenButton.addEventListener('click',togglePresentation);els.exitPresentationButton.addEventListener('click',togglePresentation);document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('presentation')});window.addEventListener('keydown',event=>{if(event.target.matches('input'))return;if(event.code==='Space'){event.preventDefault();togglePlay()}if(event.key==='ArrowRight')jumpToPage(currentPage+1);if(event.key==='ArrowLeft')jumpToPage(currentPage-1);if(event.key.toLowerCase()==='f')togglePresentation()});updateControls();
